language: python
sudo: false
dist: trusty
python:
  - "2.7"
  - "2.7.6"
  - "3.6"
install:
  - pip install -U pip wheel
  - pip install -U setuptools
script:
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
