# Generated by Django 5.2.1 on 2025-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20150918_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('pt', 'Portuguese')], default='en', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('IN', 'Institution'), ('CA', 'Country Administrator'), ('IC', 'ICAP')], max_length=2),
        ),
    ]
