# Generated by Django 4.2.11 on 2024-05-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20150918_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('pt', 'Portuguese')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('IN', 'Institution'), ('CA', 'Country Administrator'), ('IC', 'ICAP')], max_length=2),
        ),
    ]
