# Generated by Django 5.2.1 on 2025-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20170418_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcard',
            name='intro_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='calendarchart',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='scenario_type',
            field=models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], default='G', max_length=1),
        ),
        migrations.AlterField(
            model_name='day',
            name='explanation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imageinteractive',
            name='intro_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='month',
            name='display_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='retentionratecard',
            name='intro_text',
            field=models.TextField(default=''),
        ),
    ]
